/**
 * Audit action catalogue — the only allowed `action` strings.
 * MUST match docs/conventions/audit.md (enforced by a test).
 */
export const AUDIT_ACTIONS = [
  'account.created',
  'account.updated',
  'account.ownership_transferred',
  'account.suspended',
  'account.enabled',
  'auth.email_verified',
  'auth.login',
  'auth.login_failed',
  'auth.logout',
  'auth.logout_all',
  'auth.session_revoked',
  'auth.refresh_reuse_detected',
  'auth.password_reset_requested',
  'auth.password_reset',
  'auth.password_changed',
  'team.invited',
  'team.invite_resent',
  'team.invite_revoked',
  'team.invite_accepted',
  'team.role_changed',
  'team.disabled',
  'team.enabled',
  'team.removed',
  'apikey.created',
  'apikey.revoked',
  'admin.impersonation_started',
  'admin.impersonation_stopped',
  'contacts.import_started',
  'contacts.import_completed',
  'contacts.import_canceled',
  'contacts.exported',
  'contacts.deleted',
  'contacts.bulk_updated',
  'contact.opted_out',
  'dnd.added',
  'dnd.removed',
  'custom_field.created',
  'custom_field.updated',
  'custom_field.deleted',
  'contact_list.deleted',
  'segment.deleted',
  'wallet.topup_paid',
  'wallet.adjusted',
  'wallet.settings_updated',
  'wallet.credit_limit_updated',
  'billing.profile_updated',
  'rate_card.updated',
  'agent.created',
  'agent.updated',
  'agent.deleted',
  'agent.duplicated',
  'agent.activated',
  'agent.deactivated',
  'kb.created',
  'kb.updated',
  'kb.deleted',
  'kb.source_changed',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const isAuditAction = (value: string): value is AuditAction =>
  (AUDIT_ACTIONS as readonly string[]).includes(value);
